version: '2'
services:
  gusty_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - CACHE_MAX_SIZE=10000
      - CACHE_MAX_AGE=3600000
    env_file:
      - gusty-vars.env
  nginx:
    image: nginx:1.10.2
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
